### ISSUE TITLE
Crash when add shape [1.92.0]

### ISSUE THREAD

**Issue by espilacopa** [jayanam/jmesh-tools#40]
Python: Traceback (most recent call last):
  File "C:\Users\Ludovic\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\jsculpt-tools-master\fsc_add_object_op.py", line 88, in modal
    self.add_object(context, mouse_pos)
  File "C:\Users\Ludovic\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\jsculpt-tools-master\fsc_add_object_op.py", line 115, in add_object
    hit, loc_hit, norm, face, *_ = scene.ray_cast(context.view_layer, origin, view_vector)
TypeError: Scene.ray_cast(): error with argument 1, "depsgraph" -  Function.depsgraph expected a Depsgraph type, not ViewLayer

location: <unknown location>:-1

**Comment by jayanam** [comment]
Fixed, API change in Blender 2.9
